// Generated by GAS WebApp Builder | Created by @farhanalfaizi

function doGet(e) {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('Kasir Puskesmas RME')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// ==========================================
// 0. FIREBASE CONFIGURATION & HELPER
// ==========================================
const FIREBASE_CONFIG = {
  databaseURL: "https://aplikasi-si-kasir-default-rtdb.asia-southeast1.firebasedatabase.app/", // Ganti dengan URL Database Firebase Anda
  secret: "2H9AQGotWz6rnUpZlgIuEJHiBqYyn2DvSfBQcThR", // Ganti dengan Database Secret atau API Key Anda
  projectId: "your-project-id" // Ganti dengan Project ID Firebase Anda
};

const Firebase = {
  getBaseUrl: function (path) {
    return FIREBASE_CONFIG.databaseURL + "/" + path + ".json?auth=" + FIREBASE_CONFIG.secret;
  },
  get: function (path) {
    const url = this.getBaseUrl(path);
    const res = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
    if (res.getResponseCode() === 200) return JSON.parse(res.getContentText());
    return null;
  },
  put: function (path, data) {
    const url = this.getBaseUrl(path);
    const options = { method: "put", contentType: "application/json", payload: JSON.stringify(data), muteHttpExceptions: true };
    return UrlFetchApp.fetch(url, options);
  },
  post: function (path, data) {
    const url = this.getBaseUrl(path);
    const options = { method: "post", contentType: "application/json", payload: JSON.stringify(data), muteHttpExceptions: true };
    return UrlFetchApp.fetch(url, options);
  },
  remove: function (path) {
    const url = this.getBaseUrl(path);
    const options = { method: "delete", muteHttpExceptions: true };
    return UrlFetchApp.fetch(url, options);
  }
};

// Helper untuk konversi object Firebase ke array
function getFirebaseDataAsArray(path) {
  const data = Firebase.get(path);
  if (!data) return [];
  return Object.keys(data).map(key => {
    let obj = data[key];
    obj._id = key; // menyisipkan key node jika dibutuhkan
    return obj;
  });
}

// ==========================================
// 1. SETUP DATABASE
// ==========================================
function setupDatabase() {
  const users = Firebase.get('Users');
  if (!users) {
    // Inisiasi Data Default
    Firebase.put('Users/USR-1', { UserID: 'USR-1', Nama: 'Super Admin', Username: 'admin', Password: hashPassword('Admin@2026'), Role: 'Admin', Status: 'Aktif' });
    Firebase.put('Users/USR-2', { UserID: 'USR-2', Nama: 'Kasir Utama', Username: 'kasir', Password: hashPassword('Admin@2026'), Role: 'Kasir', Status: 'Aktif' });

    Firebase.put('MasterPoli/POL-1', { PoliID: 'POL-1', NamaPoli: 'Poli Umum' });
    Firebase.put('MasterPoli/POL-2', { PoliID: 'POL-2', NamaPoli: 'Poli Gigi' });

    Firebase.put('MasterPelayanan/LAY-1', { PelayananID: 'LAY-1', NamaPelayanan: 'Pemeriksaan Dokter Umum' });
    Firebase.put('MasterPelayanan/LAY-2', { PelayananID: 'LAY-2', NamaPelayanan: 'Tindakan Ringan' });
  }
}

// ==========================================
// 2. SECURITY & AUTHENTICATION
// ==========================================
function hashPassword(password) {
  var rawHash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password);
  var txtHash = '';
  for (var i = 0; i < rawHash.length; i++) {
    var hashVal = rawHash[i];
    if (hashVal < 0) hashVal += 256;
    if (hashVal.toString(16).length === 1) txtHash += '0';
    txtHash += hashVal.toString(16);
  }
  return txtHash;
}

function generateSessionToken(username, role) {
  var token = Utilities.getUuid();
  var cache = CacheService.getScriptCache();
  cache.put('session_' + token, JSON.stringify({ username: username, role: role, created: new Date().toISOString() }), 28800);
  cache.put('user_session_' + username, token, 28800);
  return token;
}

function validateSession(token) {
  if (!token) return { valid: false, message: 'Token tidak ditemukan' };
  var cache = CacheService.getScriptCache();
  var sessionData = cache.get('session_' + token);
  if (!sessionData) return { valid: false, message: 'Session expired. Silakan login ulang.' };
  try {
    return { valid: true, data: JSON.parse(sessionData) };
  } catch (e) {
    return { valid: false, message: 'Session tidak valid' };
  }
}

function destroySession(token) {
  var cache = CacheService.getScriptCache();
  var sessionData = cache.get('session_' + token);
  if (sessionData) {
    try {
      var parsed = JSON.parse(sessionData);
      cache.remove('user_session_' + parsed.username);
    } catch (e) { }
  }
  cache.remove('session_' + token);
  return { success: true };
}

function checkLoginRateLimit(username) {
  var cache = CacheService.getScriptCache();
  var key = 'login_fail_' + username;
  var failCount = parseInt(cache.get(key) || '0');
  if (failCount >= 5) return { allowed: false, message: 'Akun terkunci karena terlalu banyak percobaan. Coba lagi 15 menit.' };
  return { allowed: true, failCount: failCount };
}

function recordLoginFailure(username) {
  var cache = CacheService.getScriptCache();
  var key = 'login_fail_' + username;
  var failCount = parseInt(cache.get(key) || '0') + 1;
  cache.put(key, String(failCount), 900);
}

function logAction(username, action, detail) {
  try {
    const timestamp = safeDateFormat(new Date()) + " " + Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'HH:mm:ss');
    Firebase.post('AuditLog', {
      Timestamp: timestamp,
      Username: username || 'SYSTEM',
      Action: action,
      Detail: String(detail || '').substring(0, 500)
    });
  } catch (e) { }
}

function loginUser(username, password) {
  var rateCheck = checkLoginRateLimit(username);
  if (!rateCheck.allowed) return { success: false, message: rateCheck.message };

  username = String(username).trim().substring(0, 50);
  password = String(password).trim();
  if (!username || !password) return { success: false, message: 'Username dan password wajib diisi.' };

  var usersArray = getFirebaseDataAsArray('Users');
  var hashedInput = hashPassword(password);

  for (var i = 0; i < usersArray.length; i++) {
    if (String(usersArray[i].Username).trim() === username && String(usersArray[i].Password).trim() === hashedInput) {
      if (String(usersArray[i].Status) !== 'Aktif') return { success: false, message: 'Akun nonaktif.' };

      CacheService.getScriptCache().remove('login_fail_' + username);
      var role = usersArray[i].Role;
      var token = generateSessionToken(username, role);
      logAction(username, 'LOGIN', 'Login sukses');

      return {
        success: true,
        token: token,
        user: { username: username, fullname: usersArray[i].Nama, role: role }
      };
    }
  }
  recordLoginFailure(username);
  return { success: false, message: 'Username atau Password salah!' };
}

function requireRole(token, allowedRoles) {
  var session = validateSession(token);
  if (!session.valid) return { authorized: false, message: session.message, sessionExpired: true };
  if (!allowedRoles.includes(session.data.role)) return { authorized: false, message: 'Akses ditolak.' };
  return { authorized: true, username: session.data.username, role: session.data.role };
}

// ==========================================
// 3. HELPERS
// ==========================================
function safeDateFormat(value) {
  if (!value) return '';
  if (value instanceof Date) return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  return String(value);
}

function sanitizeInput(value, maxLength) {
  if (!value) return '';
  return String(value).replace(/<[^>]*>/g, '').trim().substring(0, maxLength || 500);
}

// ==========================================
// 4. API ENDPOINTS
// ==========================================

function getDashboardData(token) {
  var session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

  var today = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd');
  var trxData = getFirebaseDataAsArray('Transaksi');

  var todayTotal = 0;
  var todayCount = 0;
  var recentTrx = [];

  var reversedTrx = [...trxData].reverse();

  for (var i = 0; i < reversedTrx.length; i++) {
    let t = reversedTrx[i];
    if (t.Tanggal === today) {
      todayTotal += Number(t.TotalBayar) || 0;
      todayCount++;
    }
    if (recentTrx.length < 10) {
      recentTrx.push(t);
    }
  }

  // Monthly Chart Data (Last 7 Days)
  var chartData = {};
  for (var i = 6; i >= 0; i--) {
    let d = new Date();
    d.setDate(d.getDate() - i);
    chartData[Utilities.formatDate(d, Session.getScriptTimeZone(), 'yyyy-MM-dd')] = 0;
  }

  trxData.forEach(t => {
    if (chartData[t.Tanggal] !== undefined) {
      chartData[t.Tanggal] += Number(t.TotalBayar) || 0;
    }
  });

  var imports = getFirebaseDataAsArray('RiwayatImport');
  var lastImport = imports.length > 0 ? imports[imports.length - 1] : null;

  return {
    success: true,
    data: {
      todayTotal: todayTotal,
      todayCount: todayCount,
      recentTrx: recentTrx,
      chartData: chartData,
      lastImport: lastImport
    }
  };
}

function processImport(token, payload) {
  var session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(15000);

    var trxData = getFirebaseDataAsArray('Transaksi');
    var existingSet = new Set(trxData.map(t => String(t.NoTransaksi)));

    var importID = 'IMP-' + new Date().getTime();
    var dateNow = safeDateFormat(new Date());
    var dateTimeNow = dateNow + " " + Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'HH:mm:ss');
    var berhasil = 0;
    var gagal = 0;

    payload.data.forEach(item => {
      // Validasi Khusus Umum
      let jenis = String(item.JenisPasien || '').trim();
      let noTrx = String(item.NoTransaksi || '').trim();

      if (!noTrx || (jenis.toLowerCase() !== 'umum' && jenis.toLowerCase() !== 'pasien umum')) {
        gagal++;
        return;
      }

      if (existingSet.has(noTrx)) {
        gagal++;
        return;
      }

      var trxId = 'TRX-' + new Date().getTime() + '-' + Math.floor(Math.random() * 1000);

      Firebase.put('Transaksi/' + trxId, {
        TransaksiID: trxId,
        NoTransaksi: noTrx,
        Tanggal: item.Tanggal || dateNow,
        Jam: item.Jam || '',
        NoRM: item.NoRM || '',
        NamaPasien: sanitizeInput(item.NamaPasien, 100),
        JenisPasien: 'Umum', // Force to Umum
        PoliID: item.PoliID || '',
        DokterID: item.DokterID || '',
        PelayananID: item.PelayananID || '',
        NamaPelayanan: sanitizeInput(item.NamaPelayanan, 100),
        Tarif: Number(item.Tarif) || 0,
        Diskon: Number(item.Diskon) || 0,
        TotalBayar: Number(item.TotalBayar) || 0,
        MetodePembayaran: item.MetodePembayaran || 'Tunai',
        StatusPembayaran: item.StatusPembayaran || 'Lunas',
        TanggalImport: dateTimeNow,
        ImportID: importID
      });

      existingSet.add(noTrx);
      berhasil++;
    });

    // Log Import
    Firebase.put('RiwayatImport/' + importID, {
      ImportID: importID,
      NamaFile: sanitizeInput(payload.fileName, 100),
      TanggalImport: dateTimeNow,
      JumlahData: payload.data.length,
      Berhasil: berhasil,
      Gagal: gagal,
      UserID: session.data.username
    });

    logAction(session.data.username, 'IMPORT', 'File: ' + payload.fileName + ' (' + berhasil + ' sukses)');

    return { success: true, berhasil: berhasil, gagal: gagal };

  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function getTransaksiData(token) {
  var session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };
  return { success: true, data: getFirebaseDataAsArray('Transaksi') };
}

function deleteTransaksi(token, trxId) {
  var auth = requireRole(token, ['Admin']);
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var data = Firebase.get('Transaksi/' + trxId);
    if (data) {
      Firebase.remove('Transaksi/' + trxId);
      logAction(auth.username, 'DELETE_TRX', 'ID: ' + trxId);
      return { success: true };
    }
    return { success: false, message: 'Data tidak ditemukan.' };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function getMasterDataAll(token) {
  var session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

  return {
    success: true,
    poli: getFirebaseDataAsArray('MasterPoli'),
    dokter: getFirebaseDataAsArray('MasterDokter'),
    layanan: getFirebaseDataAsArray('MasterPelayanan')
  };
}

// Universal Master Data Saver
function saveMasterData(token, sheetName, payload) {
  var auth = requireRole(token, ['Admin']);
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);

    if (payload.isEdit === 'true') {
      var exist = Firebase.get(sheetName + '/' + payload.id);
      if (exist) {
        var rowData = {
          [sheetName === 'MasterPoli' ? 'PoliID' : sheetName === 'MasterDokter' ? 'DokterID' : 'PelayananID']: payload.id,
          [sheetName === 'MasterPoli' ? 'NamaPoli' : sheetName === 'MasterDokter' ? 'NamaDokter' : 'NamaPelayanan']: sanitizeInput(payload.nama, 100)
        };
        if (sheetName === 'MasterDokter') rowData.PoliID = payload.poliId;

        Firebase.put(sheetName + '/' + payload.id, rowData);
        logAction(auth.username, 'UPDATE_MASTER', sheetName + ' : ' + payload.nama);
        return { success: true };
      }
      return { success: false, message: 'Data tidak ditemukan' };
    } else {
      var newId = '';
      if (sheetName === 'MasterPoli') newId = 'POL-' + new Date().getTime();
      if (sheetName === 'MasterDokter') newId = 'DOK-' + new Date().getTime();
      if (sheetName === 'MasterPelayanan') newId = 'LAY-' + new Date().getTime();

      var rowData = {
        [sheetName === 'MasterPoli' ? 'PoliID' : sheetName === 'MasterDokter' ? 'DokterID' : 'PelayananID']: newId,
        [sheetName === 'MasterPoli' ? 'NamaPoli' : sheetName === 'MasterDokter' ? 'NamaDokter' : 'NamaPelayanan']: sanitizeInput(payload.nama, 100)
      };
      if (sheetName === 'MasterDokter') rowData.PoliID = payload.poliId;

      Firebase.put(sheetName + '/' + newId, rowData);
      logAction(auth.username, 'CREATE_MASTER', sheetName + ' : ' + payload.nama);
      return { success: true };
    }
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function deleteMasterData(token, sheetName, id) {
  var auth = requireRole(token, ['Admin']);
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var exist = Firebase.get(sheetName + '/' + id);
    if (exist) {
      Firebase.remove(sheetName + '/' + id);
      logAction(auth.username, 'DELETE_MASTER', sheetName + ' ID: ' + id);
      return { success: true };
    }
    return { success: false, message: 'Data tidak ditemukan.' };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function getImportHistory(token) {
  var session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };
  return { success: true, data: getFirebaseDataAsArray('RiwayatImport') };
}